name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # 매 5분마다 실행
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest

    steps:
      - name: Curl your Streamlit app
        run: |
          curl -s -A "Mozilla/5.0" https://maetanarticle.streamlit.app/
