name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # 매 5분마다 실행 (UTC 기준)
  workflow_dispatch:        # 수동 실행도 가능하게 설정

jobs:
  ping-app:
    runs-on: ubuntu-latest

    steps:
      - name: Ping the Streamlit app
        run: |
          curl -s -A "Mozilla/5.0" https://maetanarticle.streamlit.app/
